services:
  db-smart-env:
    image: mongo:6.0
    container_name: "db-smart-env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=station
      - MONGO_INITDB_ROOT_PASSWORD=b268iaTJ
      - MONGO_INITDB_DATABASE=vigilante
    networks:
      - smart-env-network
  api:
    build: ./app
    container_name: "api-smart-env"
    environment:
      MONGO_URI: "mongodb://station:b268iaTJ@mongo:27017/vigilante?authSource=admin"
      DB_NAME: "vigilante"
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db
    networks:
      - smart-env-network
networks:
  smart-env-network:
    driver: bridge
